agiledev-students-spring-2023/final-project-concerts-io

CONTRIBUTING.md
README.md

Finished project setup and sprint planning portion of sprint 0

Project setup

---

front-end/package-lock.json
front-end/package.json
front-end/src/About.js
front-end/src/App.js
front-end/src/ArtistStandalone.js
front-end/src/ConcertStandalone.js
front-end/src/FavoriteArtists.js
front-end/src/Home.js
front-end/src/Profile.js
front-end/src/SavedConcerts.js

I setup the browser router in app.js with all the routes, and I made empty files of all the react components that all the routes lead to. Runs fine on my machine, and there should be no content shown because the components are empty.

Implemented routing for all pages

---

front-end/package-lock.json
front-end/package.json
front-end/src/App.js
front-end/src/pages/Home.js

Home Page is inside of the pages folder and the app routes to it as the default address

Set Up Home Page Template And Routing

---

front-end/src/App.js
front-end/src/components/Menu.css
front-end/src/components/Menu.js
front-end/src/pages/Home.js

Implemented and styled a simple menu component to be used across all pages

User-story/5/task/25/menu-component

---

front-end/src/App.js
front-end/src/components/ArtistComponent.js
front-end/src/pages/FavoriteArtists.js

Working on good on my machine, please check if it's all good on yours

Added fav artists page and fixed error in app.js with menu component

---

front-end/package.json
front-end/src/components/FavArtistsMini.js
front-end/src/pages/FavoriteArtists.js

put in mockaroo fetches for the favorite artists page and the mini embed in the profile

added mock api calls for favorite artists page

---

front-end/package.json
front-end/src/components/FavArtistsMini.js
front-end/src/components/SavedConcertsMini.js
front-end/src/pages/Concert.js
front-end/src/pages/SavedConcerts.js

added mock api functionality for all concert related pages

User-story/3/task/52/mock concerts api

---

front-end/src/App.js
front-end/src/pages/Connection.css
front-end/src/pages/Connection.js

hi i just build the api connection page. its ugly but hope it make sense

building connection page

---

front-end/src/App.js
front-end/src/pages/EditProfile.js
front-end/src/pages/Login.js
front-end/src/pages/Profile.js
front-end/src/pages/Register.js

Edit profile and registration functionality working good on my end. Note that every field in the edit profile form must have text before submitting.

Implemented edit-profile and register pages

---

back-end/app.js
back-end/package.json
back-end/server.js

User story/22/task/77/express server setup

---

back-end/app.js
back-end/helperFunctions.js
back-end/package.json
front-end/package.json
front-end/src/pages/Connection.js

Added routes for connecting to spotify api and implemented functionality to authorize the user and retrieve favorite artist data.

User story/22/task/78/setup requests to spotify api

---

.eslintrc.json
.prettierrc
back-end/app.js
back-end/server.js
package.json

I installed eslint and prettier for code linting and formatting. I followed this linkedIn learning tutorial: [https://www.linkedin.com/learning/building-a-website-with-node-js-and-express-js-3/setting-up-eslint-and-prettier?autoSkip=true&autoplay=true&resume=false&u=2131553](url).
Everything should be working well, but for vscode integration you have to install the eslint and prettier extension and then change the settings to use them. Everything is covered in the tutorial I linked, and it should be free to use if you sign in through nyu.

Setup eslint and prettier as devDependencies

---

back-end/app.js
back-end/package.json
front-end/src/pages/Artist.js
front-end/src/pages/EditProfile.js
front-end/src/pages/Login.js

Created backend routes for the profile page and linked the react frontend to them. Also fixed some issues from the quality report on the previous spritn

User story/10/task/88/create route for profile page

---

back-end/app.js
back-end/routes/Artist.js
back-end/routes/Concert.js
front-end/src/pages/Artist.js
front-end/src/pages/Concert.js

routers for individual artist and concert page seemingly working

individual concert router and artist router working from backend

---

back-end/app.js
front-end/src/App.js
front-end/src/pages/Home.js
front-end/src/pages/Recommended.js

Added backend routing for recommended cocnerts

User story/22/task/92/add backend routes for recommended concerts

---

back-end/app.js
back-end/controllers/TicketMaster.js
back-end/controllers/TicketMasterMany.js
front-end/src/pages/Concert.css
front-end/src/pages/Concert.js
front-end/src/pages/Home.js
front-end/src/pages/Recommended.js

ticketmaster integration foundation layed!

User story/22/task/102/ticketmaster api

---

back-end/package.json
back-end/routes/SavedConcerts.js
back-end/tests/SavedConcerts.test.js

added unit tests for saved concerts

---

back-end/app.js
back-end/routes/Recommended.js
back-end/test/app-test.js

18 tests should passing when you run "npm test"

User story22/task/99/write unit tests for recommended concerts route

---

back-end/addFavoriteArtistsToUser.js
back-end/artistUtils.js
back-end/models/Artist.js
back-end/testAddFavoriteArtistsToUser.js

i added a file to test with sample data. use node testAddFavoriteArtistsToUser.js

User story/4/task/132/convert users favorite artists to artist documents and store in user document

---

back-end/app.js
back-end/models/Artist.js
back-end/routes/Artist.js
back-end/routes/FavoriteArtists.js
front-end/src/components/ArtistComponent.js
front-end/src/components/FavArtistsMini.js
front-end/src/pages/Artist.js
front-end/src/pages/FavoriteArtists.js

I changed the backend FavoriteArtists and Artist routes to send back actual data from the database. Login in from the react page with username: tester and password: abcd1234. Favorite artists page should show two testerArtist artists and then clicking on them going to an artist page.

User story/4/task/139/change backend to send back user's favorite artists

---

back-end/app.js
back-end/models/concert.js
back-end/routes/SaveConcert.js
back-end/routes/SavedConcerts.js
back-end/routes/TicketMaster.js
front-end/src/pages/Concert.js

saving concert functionality implemented

---

back-end/app.js
back-end/models/concert.js
back-end/routes/ConnectionPage.js
back-end/routes/FavoriteArtists.js
back-end/routes/LastFmCallback.js
back-end/routes/LastFmConnect.js
back-end/routes/Profile.js
back-end/routes/SaveConcert.js
back-end/routes/SavedConcerts.js
back-end/routes/SpotifyCallback.js
back-end/routes/SpotifyConnnect.js
back-end/routes/TicketMaster.js
front-end/src/components/FavArtistsMini.css
front-end/src/pages/Concert.js
front-end/src/pages/Connection.js

got lastfm api data stored into user object and displayed once connected. Going to move to a different task before spotify

User story/22/task/143/store-just-lastfm-data

---

back-end/routes/SpotifyCallback.js
back-end/routes/SpotifyConnnect.js
front-end/src/pages/Connection.js

Seems to work fine so long as user is registered in the spotify backend

User story/22/task/150/store-spotify-data

---

back-end/package.json
back-end/routes/Artist.js
back-end/routes/Authentication.js
back-end/routes/Concert.js
back-end/routes/EditProfile.js
back-end/routes/FavoriteArtists.js
back-end/routes/Profile.js
back-end/routes/Recommended.js
back-end/routes/SavedConcerts.js
back-end/routes/TicketMaster.js
back-end/routes/TicketMasterMany.js
back-end/routes/TicketmasterSearch.js
front-end/src/components/FavArtistsMini.js
front-end/src/components/SavedConcertsMini.js
front-end/src/pages/Artist.js
front-end/src/pages/Concert.js
front-end/src/pages/EditProfile.js
front-end/src/pages/FavoriteArtists.js
front-end/src/pages/Home.js
front-end/src/pages/Login.js
front-end/src/pages/Profile.js
front-end/src/pages/Recommended.js
front-end/src/pages/Register.js
front-end/src/pages/SavedConcerts.js

Got rid of all backup data and setup frontend to display error messages when appropriate

User story/22/task/153/get rid of backup data

---

back-end/models/concert.js

renamed concert module to be capital for digital ocean

renamed concert

---

front-end/src/App.css
front-end/src/components/Menu.css
front-end/src/pages/Concert.css
front-end/src/pages/Concert.js
front-end/src/pages/Recommended.css

did some styling for the menu wrapper and also the concert page. work in progress tho

User story/5/task/168/css touch up across site

---

front-end/src/App.css
front-end/src/components/ConcertComponent.css
front-end/src/components/FavArtistsMini.js
front-end/src/components/Menu.css
front-end/src/components/SavedConcertsMini.js
front-end/src/index.css
front-end/src/pages/About.css
front-end/src/pages/Concert.css
front-end/src/pages/Recommended.css

just changed the fetches in the mini components to direct to the env variable

changed two faulty routes in favartistsmini and savedconcertsmini

---

back-end/app.js
back-end/routes/ManualEntry.js
front-end/src/App.js
front-end/src/pages/Connection.js
front-end/src/pages/ManualEntry.js

added manual artist page for users to just enter their top artists

User story/22/task/185/manual artist adding

---

back-end/app.js
back-end/routes/Authentication.js
back-end/routes/ManualEntry.js
back-end/routes/TicketmasterSearch.js
back-end/test/app-test.js
front-end/src/pages/Artist.js
front-end/src/pages/EditProfile.js
front-end/src/pages/FavoriteArtists.css
front-end/src/pages/FavoriteArtists.js
front-end/src/pages/Home.css
front-end/src/pages/Home.js
front-end/src/pages/ManualEntry.css
front-end/src/pages/ManualEntry.js
front-end/src/pages/Recommended.css
front-end/src/pages/Recommended.js
front-end/src/pages/SavedConcerts.css
front-end/src/pages/SavedConcerts.js

Added some more styling changes and fixes and wrote a few unit tests

User story/10/task/160/edit profile and auth unit tests

---

front-end/src/pages/Concert.js

super small change for grammar idk this was bothering me

changed 'at' to 'in' in concert pages

---

README.md
back-end/readme.md
front-end/README.md

User story/22/task/187/markdown updates

---

front-end/src/pages/Concert.css
front-end/src/pages/Concert.js
front-end/src/pages/Home.css
front-end/src/pages/Recommended.css

added media queries for logo so content isn't obscured in desktop mode

modifed css with media queries to make site usable on desktop

---

front-end/src/components/Menu.css
front-end/src/components/Menu.js

User can now click on the icons in the menu instead of just the links to go to other pages

fixed menu links
